# Generated by Django 4.0.7 on 2024-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=150)),
                ('joining_date', models.DateField()),
                ('educational_background', models.JSONField(blank=True)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
